apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observium.fullname" . }}
  labels:
    {{- include "observium.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "observium.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "observium.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "observium.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: OBSERVIUM_ADMIN_USER
              value: {{ .Values.observium.admin.user }}
            - name: OBSERVIUM_ADMIN_PASS
              value: {{ .Values.observium.admin.password }}
            - name: OBSERVIUM_DB_HOST
              value: {{ .Values.observium.db.host }}
            - name: OBSERVIUM_DB_USER
              value: {{ .Values.observium.db.user }}
            - name: OBSERVIUM_DB_PASS
              value: {{ .Values.observium.db.password }}
            - name: OBSERVIUM_DB_NAME
              value: {{ .Values.observium.db.name }}
            - name: OBSERVIUM_BASE_URL
              value: {{ .Values.observium.base_url }}
            - name: TZ
              value: {{ .Values.observium.tz }}
            - name: SERVER_NAME
              value: {{ .Values.observium.server_name }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: observium-rrd
              mountPath: /opt/observium/rrd
            - name: observium-logs
              mountPath: /opt/observium/logs
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: observium-rrd
          persistentVolumeClaim:
            claimName: {{ include "observium.fullname" . }}-rrd
        - name: observium-logs
          persistentVolumeClaim:
            claimName: {{ include "observium.fullname" . }}-logs
