apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "observium.fullname" . }}-logs
  labels:
  {{- include "observium.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
  {{- if .Values.persistence.logs.storageClassName }}
  storageClassName: {{ .Values.persistence.logs.storageClassName }}
  {{- end }}
