apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homebridge.fullname" . }}
  labels:
  {{- include "homebridge.labels" . | nindent 4 }}
data:
  {{- with .Values.homebridge.config }}
  config.json:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.homebridge.package }}
  package.json:
  {{- toYaml . | nindent 4 }}
  {{- end }}
