ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    external-dns: "true"
    external-dns.alpha.kubernetes.io/access: public
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/target: 130.180.93.142
  hosts:
    - host: scrypted.krizic.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: scrypted-tls
      hosts:
        - scrypted.krizic.net
nodeSelector:
  kubernetes.io/arch: arm64
persistence:
  storageClass: longhorn
