apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "icinga2.fullname" . }}-icinga2-cache
  labels:
  {{- include "icinga2.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.icinga2.cache.size }}
  {{- if .Values.persistence.icinga2.cache.storageClass }}
  storageClassName: {{ .Values.persistence.icinga2.cache.storageClass }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "icinga2.fullname" . }}-icinga2-etc
  labels:
  {{- include "icinga2.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.icinga2.etc.size }}
  {{- if .Values.persistence.icinga2.etc.storageClass }}
  storageClassName: {{ .Values.persistence.icinga2.etc.storageClass }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "icinga2.fullname" . }}-icinga2-lib
  labels:
  {{- include "icinga2.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.icinga2.lib.size }}
  {{- if .Values.persistence.icinga2.lib.storageClass }}
  storageClassName: {{ .Values.persistence.icinga2.lib.storageClass }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "icinga2.fullname" . }}-icinga2-phpsessions
  labels:
  {{- include "icinga2.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.icinga2.phpsessions.size }}
  {{- if .Values.persistence.icinga2.phpsessions.storageClass }}
  storageClassName: {{ .Values.persistence.icinga2.phpsessions.storageClass }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "icinga2.fullname" . }}-icinga2-log
  labels:
  {{- include "icinga2.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.icinga2.log.size }}
  {{- if .Values.persistence.icinga2.log.storageClass }}
  storageClassName: {{ .Values.persistence.icinga2.log.storageClass }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "icinga2.fullname" . }}-icinga2-spool
  labels:
  {{- include "icinga2.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.icinga2.spool.size }}
  {{- if .Values.persistence.icinga2.spool.storageClass }}
  storageClassName: {{ .Values.persistence.icinga2.spool.storageClass }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "icinga2.fullname" . }}-icingaweb2-etc
  labels:
  {{- include "icinga2.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.icingaweb2.etc.size }}
  {{- if .Values.persistence.icinga2.etc.storageClass }}
  storageClassName: {{ .Values.persistence.icinga2.etc.storageClass }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "icinga2.fullname" . }}-icingaweb2-log
  labels:
  {{- include "icinga2.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.icingaweb2.log.size }}
  {{- if .Values.persistence.icinga2.log.storageClass }}
  storageClassName: {{ .Values.persistence.icinga2.log.storageClass }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "icinga2.fullname" . }}-apache2-log
  labels:
  {{- include "icinga2.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.apache2.log.size }}
  {{- if .Values.persistence.apache2.log.storageClass }}
  storageClassName: {{ .Values.persistence.apache2.log.storageClass }}
  {{- end }}
