apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "checkmk.fullname" . }}-sites
  labels:
  {{- include "checkmk.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
