apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oscam.fullname" . }}
  labels:
    {{- include "oscam.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "oscam.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "oscam.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "oscam.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostNetwork: {{ .Values.network.hostNetwork }}
      initContainers:
        - name: oscam-copy-defaults
          image: busybox
          command:
            - "/bin/sh"
          args:
            - "-c"
            - "mkdir -p /config/oscam && cp -v /default/* /config/oscam/"
          volumeMounts:
            - name: {{ include "oscam.volume.default" . }}
              mountPath: /default
            - name: {{ include "oscam.volume.config" . }}
              mountPath: /config
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
            - name: cccam
              containerPort: 10000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: {{ include "oscam.volume.config" . }}
              mountPath: /config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "oscam.volume.config" . }}
          persistentVolumeClaim:
            claimName: {{ include "oscam.volume.config" . }}
        - name: {{ include "oscam.volume.default" . }}
          configMap:
            name: {{ include "oscam.volume.default" . }}
