apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "proxy.fullname" . }}
subsets:
  - addresses:
      - ip: {{ .Values.endpoint.ipAddress }}
    ports:
      - port: {{ .Values.endpoint.port }}
        protocol: TCP
