apiVersion: v1
kind: Service
metadata:
  name: {{ include "oscam.fullname" . }}-nodeport
  labels:
    {{- include "oscam.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    {{- range $entry := .Values.network.ports }}
    - port: {{ $entry.port }}
      targetPort: {{ $entry.port }}
      protocol: TCP
      name: {{ $entry.name }}
    {{- end }}
  selector:
    {{- include "oscam.selectorLabels" . | nindent 4 }}
