apiVersion: v1
kind: Secret
metadata:
  name: {{ include "copilot-metrics-exporter.fullname" . }}
  labels:
    {{- include "copilot-metrics-exporter.labels" . | nindent 4 }}
data:
  GITHUB_TOKEN: "{{ .Values.github.token | b64enc }}"
