apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "joomla.fullname" . }}
  labels:
    {{- include "joomla.labels" . | nindent 4 }}
data:
  JOOMLA_DB_HOST: {{ .Values.database.host | quote}}
  JOOMLA_DB_USERNAME: {{ .Values.database.username | quote }}
  JOOMLA_DB_NAME: {{ .Values.database.name | quote }}
