apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "joomla.fullname" . }}
  labels:
  {{- include "joomla.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
