api: v1
kind: Secret
metadata:
  name: {{ include "joomla.fullname" . }}
  labels:
    {{- include "joomla.labels" . | nindent 4 }}
data:
  JOOMLA_DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
