apiVersion: v1
kind: Service
metadata:
  name: {{ include "scrypted.fullname" . }}
  labels:
    {{- include "scrypted.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: http
  selector:
    {{- include "scrypted.selectorLabels" . | nindent 4 }}
